apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mattermost-db-secret
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mattermost-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_CONNECTION_STRING
      remoteRef:
        key: mattermost/database
        property: DB_CONNECTION_STRING
    - secretKey: password
      remoteRef:
        key: mattermost/database
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: mattermost/database
        property: postgres-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
      key: mattermost/minio
      property: accesskey

  - secretKey: secret_key
    remoteRef:
      key: mattermost/minio
      property: secretkey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mattermost-minio-secret
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mattermost-minio-secret
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: mattermost/minio
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: mattermost/minio
        property: secretkey